#  Human Evaluation

***Multi-Criteria Scoring:** Human raters grade output pairs on a strict 0–3 scale across 5 dimensions: *Relevance, Faithfulness, Latency, Readability,* and *Perplexity*.

### Human Evaluation Guidelines:

#### 1- Relevance
Definition: Measures how well the AI’s answer addresses the specific question asked by the student. It penalizes answers that are off-topic, incomplete, or dodge the question.

	•	Score 3 (Perfect): The AI directly and completely answers the student’s question. It provides exactly what was asked without unnecessary filler.
	•	Score 2 (Partial/Good): The AI addresses the main topic but misses a minor part of the student's question, or includes slightly irrelevant extra information.
	•	Score 1 (Poor): The AI talks about the general topic but fails to answer the specific question asked (e.g., the student asks "How" and the AI answers "When").
	•	Score 0 (Irrelevant): The answer is completely off-topic, talks about something else entirely, or says "I don't know" when the information is basic.


#### 2- Faithfulness (Truthfulness / Groundedness)
Definition: Measures if the AI's answer is strictly based on the provided PDF document chunks. It checks for hallucinations (making things up). Note: An answer can be relevant but unfaithful if the AI makes up a fake fact to answer the question.

	•	Score 3 (Completely Faithful): Every single fact, date, or claim in the AI's response is directly supported by the provided document chunks. No outside knowledge or assumptions are added.
	•	Score 2 (Mostly Faithful): The core answer is fully supported by the document, but the AI adds a small, harmless piece of outside information or common knowledge that wasn't explicitly in the PDF.
	•	Score 1 (Low Faithfulness): The AI introduces significant information, equations, or facts that cannot be found anywhere in the provided document, or mildly distorts what the document says.
	•	Score 0 (Hallucination): The AI completely fabricates information, contradicts the source document, or claims the document says something it flatly does not.
    

#### -3 Latency (Perceived Speed)
Definition: Measures how the generation speed impacts the student's user experience. Grade this based on your perceived wait time during testing.

	•	Score 3 (Instant): The response appears almost immediately (under 2 seconds) or streams so smoothly that there is zero disruption to a student's train of thought.
	•	Score 2 (Acceptable Delay): There is a brief, noticeable pause (3–5 seconds) before the answer appears. It is slightly annoying but acceptable for an educational tool.
	•	Score 1 (Frustratingly Slow): The delay is significant (6–12 seconds). A student would likely lose focus, get distracted, or assume the app is lagging.
	•	Score 0 (Unusable / Timeout): The system takes longer than 12 seconds to respond, throws a loading error, or forces you to refresh the page.
    

#### 4- Readability (Formatting & Structure)
Definition: Measures how well the information is structured for a student. It evaluates formatting, visual layout, and pedagogical clarity (e.g., use of bullet points, bold text, and proper paragraph breaks).

	•	Score 3 (Excellent Structure): Highly scannable. It uses bullet points, numbered lists, or bold text appropriately to highlight key educational concepts. It looks clean and easy to study.
	•	Score 2 (Average Structure): The response is organized into readable paragraphs, but it lacks visual anchors like bullet points or bold text that would make it easier for a student to quickly digest.
	•	Score 1 (Poor Structure): The response is a massive, daunting "wall of text" with no paragraph breaks, or it contains messy layout artifacts (like random spaces or broken characters) from the PDF conversion.
	•	Score 0 (Unreadable): The formatting is completely broken. Sentences are randomly cut off, text overlaps, or the layout makes it impossible to read comfortably.

#### 5- Perplexity (Human Fluency & Tone)
Definition: In human evaluation, this measures how natural, grammatically correct, and cohesive the language is. It evaluates if the AI sounds like a professional human teacher or a broken machine.

	•	Score 3 (Natural/Human-like): The language is flawless. It reads like it was written by a human educator. Perfect grammar, smooth transitions, and an encouraging, professional tone.
	•	Score 2 (Slightly Robotic): The text is grammatically correct and fully understandable, but the phrasing feels a bit robotic, clinical, or repetitive.
	•	Score 1 (Awkward / Clunky): The phrasing is highly unnatural. Thoughts are disjointed, sentences are clunky, or there are clear grammatical errors that force you to reread the sentence to understand it.
	•	Score 0 (Gibberish): Complete word salad. The sentences make no linguistic sense, words are used completely out of context, or the text is a repetitive loop.

### Evaluation Golden Rules for Raters:

	1.	Keep criteria independent: An AI can give a beautifully formatted (Readability = 3) and perfectly fluent (Perplexity = 3) answer, but make up a complete lie (Faithfulness = 0). Grade each category strictly on its own definition.
	2.	Read the Source Document Chunks First: Do not grade Faithfulness based on what you know to be true; grade it only on whether that information exists in the specific PDF chunks provided for that query.

# Understanding Inter-Annotator Agreement (Cohen's Kappa)

### 1. What is Cohen's Kappa (κ)?
Cohen’s Kappa is a statistical metric used to measure agreement between exactly two raters who are grading items into distinct categories (like our 0, 1, 2, 3 scores).
Unlike simple percentage agreement (e.g., "They agreed 80% of the time"), Cohen's Kappa subtracts the probability of accidental agreement. If both raters blindly guessed "3" all day, their percentage agreement would be high, but their Kappa score would be 0.


### 2. How to Interpret the Kappa Score (κ)
The resulting score falls between -1 and 1, though in practice it is usually between 0 and 1:

	•	0.81 – 1.00: Almost Perfect Agreement. Your guidelines are crystal clear, and your raters are completely aligned.
	•	0.61 – 0.80: Substantial Agreement. This is the gold standard target for AI evaluation datasets. The data is highly reliable.
	•	0.41 – 0.60: Moderate Agreement. Acceptable, but indicates that some metrics (likely Perplexity or Readability) are too subjective. You need to clarify your guidelines.
	•	Below 0.40: Fair to Poor Agreement. The raters are contradicting each other. Your evaluation data cannot be trusted. You must retrain the raters.

# Data Processing/Gathering

In [122]:
import pandas as pd
from sklearn.metrics import cohen_kappa_score
import numpy as np
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

### Evaluated chat number 1

In [123]:
evaluater_A= pd.read_csv('Evaluation1_mervat.csv')
evaluater_B= pd.read_csv('Evaluation1_nesreen.csv')
chat_df1= pd.read_csv('chat_df.csv')

In [124]:
evaluater_A.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    query_number  14 non-null     int64
 1    Relevance     14 non-null     int64
 2   Faithfulness   14 non-null     int64
 3    Latency       14 non-null     int64
 4   Readability    14 non-null     int64
 5   Preplexity     14 non-null     int64
 6   date           14 non-null     object
dtypes: int64(6), object(1)
memory usage: 916.0+ bytes

In [125]:
chat_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   question                13 non-null     object
 1   answer                  13 non-null     object
 2   execution_time_seconds  13 non-null     float64
 3   retrieved_context       13 non-null     object
dtypes: float64(1), object(3)
memory usage: 548.0+ bytes

In [126]:
chat_df1.head(2)

,question,answer,execution_time_seconds,retrieved_context
0,"اشرح retriever, بالأمثلة",أنا أعتذر، ولكن في هذه الحالة لا يمكنني مساعدتك. المعلومات التي تحتاجها لا تظهر في المحتوى الذي تم تحميل.,197.31,Retrieval \nAugmented \nGeneration \n(RAG)\nDr. Tamer Arafa\n\nhelp you respond. <retrieved articles>”\nRetriever\nKnowledge \nBase\n14\n\nMiss valuable information\n●\nNo perfect solution\nRetriever usually doesn’t perfectly rank documents\n●\nMonitor and experiment\nChange settings to find what works\n19\n\nRetrieval Augmented Generation\n9
1,"explain what the Retriever is, with examples","The Retriever is a component of an AI system that helps retrieve relevant information from knowledge bases or databases to improve the performance and quality of language generation tasks. It manages a knowledge base containing trusted information and finds the most relevant documents for specific queries.\n\nHere are some examples:\n\n1. **Relevance vs Irrelevance Tradeoff**: Imagine you're trying to find an article about how to make homemade pizza. You could ask your AI assistant, ""What is the best recipe for making pizza?"" The Retriever would likely return a document that provides comprehensive tips on making various types of pizzas, including homemade ones.\n\n2. **Returning Every Document?** Suppose you want to know more about different types of dogs. If you asked, ""What are all the breeds of dogs,"" the Retriever might return every single article it has ever seen about dog breeds, which could be thousands or even millions of documents. This approach would cover everything but wouldn't necessarily provide the most relevant information for your specific query.\n\n3. **Returning the Single Highest Ranked Document**: If you asked, ""What is the best way to start a business?"" The Retriever might return a document that provides the most comprehensive and up-to-date advice on starting a successful business, rather than just one article about dog breeds or pizza recipes.\n\n4. **No Perfect Solution**: Sometimes there's no perfect solution because finding the right balance between relevance and irrelevance can be challenging. For example, if you're looking for information about climate change but don't want to see articles that are too focused on politics, the Retriever might struggle to find just the right mix of relevant and irrelevant documents.\n\n5. **Monitoring and Experimentation**: The Retriever is designed to monitor its performance and experiment with different settings to improve how it ranks documents. This means tweaking parameters like ""relevance vs irrelevance"" or adjusting the number of documents returned, so that over time, it becomes better at finding the most relevant information for your queries.\n\nIn summary, the Retriever helps you find exactly what you need by balancing relevance and other factors to provide the best possible answers.",405.84,help you respond. <retrieved articles>”\nRetriever\nKnowledge \nBase\n14\n\nRetriever\n●\nManages knowledge base of trusted \ninformation\n●\nFinds the most relevant Information \nand shares information with the LLM\n●\nImproves generation\nRetriever\nKnowledge \nBase\n8\n\nRetriever Tradeoffs\n●\nRelevance vs irrelevance\nNeed to return relevant documents and withhold irrelevant ones\n●\nReturn every document?\nMountains of irrelevant docs. Wastes context window\n●\nReturn the single highest ranked document?\nMiss valuable information\n●\nNo perfect solution\n\nMiss valuable information\n●\nNo perfect solution\nRetriever usually doesn’t perfectly rank documents\n●\nMonitor and experiment\nChange settings to find what works\n19

In [127]:
chat_df1.tail(1)

,question,answer,execution_time_seconds,retrieved_context
12,ما هى قاعدة بيانات المتجهات؟,قاعدة البيانات المتجهات (Graph Database) هي نوع من أنواع بيئة المخزن التي تستخدم مفاهيم الجذور والارتباطات (العلاقات) لتخزين وبحث البيانات. هذه القاعدة البيانات تسمح بالتعامل مع البيانات التي تتكون من الأشخاص، الأماكن، العلاقات بينهم، أو أي شيء آخر يرتبط ببعضه.\n\nمثال على استخدام قاعدة البيانات المتجهات هو في التعامل مع البيانات المتعلقة بالشبكات الاجتماعية. إذا كان هناك شخص واحد الذي يمتلك علاقات (متشابكة) مع العديد من الأشخاص الآخرين، يمكننا استخدام قاعدة البيانات المتجهات لتخزين هذه العلاقات وبحثها بسهولة.\n\nبشكل عام، القاعدة البيانات المتجهة تستخدم في العديد من التطبيقات مثل: \n\n1. التعامل مع البيانات الاجتماعية (مثل معلومات التواصل الاجتماعي)\n2. التحليل البيئي (الذي يتعامل مع البيانات المتعلقة بالمناخ والبيئة)\n3. البحث العلمي (الذي يتعامل مع البيانات التي تتضمن العلاقات بين الأشخاص أو الأشياء)\n4. تطوير الاتجاهات في الأعمال التجارية (مثل تحديد العلامات التجارية وتحليل التغيرات في السوق)\n\nبشكل عام، القاعدة البيانات المتجهة هي مفهوم مهم في مجال البيانات الكبيرة والذكاء الصناعي حيث تستخدم لمعالجة البيانات التي تتكون من العلاقات والتفاعلات بين الأشياء.,981.25,Retrieval \nAugmented \nGeneration \n(RAG)\nDr. Tamer Arafa\n\nhelp you respond. <retrieved articles>”\nRetriever\nKnowledge \nBase\n14\n\nSearch Techniques\n1. Document A\n2. Document B\n3. Document C\n4. Document D\n…\n1. Document C\n2. Document B\n3. Document X\n4. Document Y\n…\n1. Document A\n2. Document B\n3. Document C\n4. Document D\n…\n1. Document C\n2. Document B\n3. Document X\n4. Document Y\n…\nKeyword \nSearch\nSemantic \nSearch\n\nRespond based on \nyour knowledge\nSynthesize \nresearch\n2

In [128]:
chat_df1['query_number'] = chat_df1.index

In [129]:
chat_df1.head(1)

,question,answer,execution_time_seconds,retrieved_context,query_number
0,"اشرح retriever, بالأمثلة",أنا أعتذر، ولكن في هذه الحالة لا يمكنني مساعدتك. المعلومات التي تحتاجها لا تظهر في المحتوى الذي تم تحميل.,197.31,Retrieval \nAugmented \nGeneration \n(RAG)\nDr. Tamer Arafa\n\nhelp you respond. <retrieved articles>”\nRetriever\nKnowledge \nBase\n14\n\nMiss valuable information\n●\nNo perfect solution\nRetriever usually doesn’t perfectly rank documents\n●\nMonitor and experiment\nChange settings to find what works\n19\n\nRetrieval Augmented Generation\n9,0

In [130]:
evaluater_A.head(3)

,query_number,Relevance,Faithfulness,Latency,Readability,Preplexity,date
0,1,0,0,0,3,2,2026/06/08
1,2,3,3,1,3,3,2026/06/08
2,3,3,3,0,3,3,2026/06/08

In [131]:
evaluater_A.tail(3)

,query_number,Relevance,Faithfulness,Latency,Readability,Preplexity,date
11,12,0,0,0,2,1,2026/06/08
12,13,1,1,0,3,2,2026/06/08
13,14,0,0,0,0,0,2026/06/08

In [132]:
evaluater_B.tail(3)

,query_number,Relevance,Faithfulness,Latency,Readability,Preplexity,date
11,12,3,1,1,3,3,2026/06/08
12,13,3,0,1,3,3,2026/06/08
13,14,0,0,0,0,0,2026/06/08

In [133]:
# drop the last row in evaluation dataframe

evaluater_A = evaluater_A.iloc[:-1]
evaluater_B = evaluater_B.iloc[:-1]

In [134]:
evaluater_A.columns

Index([' query_number', ' Relevance', 'Faithfulness', ' Latency',
       'Readability', 'Preplexity', 'date '],
      dtype='object')

In [135]:
evaluater_A=evaluater_A.drop(columns=[' query_number'],axis=1)
evaluater_B=evaluater_B.drop(columns=[' query_number'],axis=1)

In [136]:
evaluater_A['query_number'] = evaluater_A.index
evaluater_B['query_number'] = evaluater_B.index

In [137]:
evaluater_A.tail(1)

,Relevance,Faithfulness,Latency,Readability,Preplexity,date,query_number
12,1,1,0,3,2,2026/06/08,12

In [138]:
chat_df1.tail(1)

,question,answer,execution_time_seconds,retrieved_context,query_number
12,ما هى قاعدة بيانات المتجهات؟,قاعدة البيانات المتجهات (Graph Database) هي نوع من أنواع بيئة المخزن التي تستخدم مفاهيم الجذور والارتباطات (العلاقات) لتخزين وبحث البيانات. هذه القاعدة البيانات تسمح بالتعامل مع البيانات التي تتكون من الأشخاص، الأماكن، العلاقات بينهم، أو أي شيء آخر يرتبط ببعضه.\n\nمثال على استخدام قاعدة البيانات المتجهات هو في التعامل مع البيانات المتعلقة بالشبكات الاجتماعية. إذا كان هناك شخص واحد الذي يمتلك علاقات (متشابكة) مع العديد من الأشخاص الآخرين، يمكننا استخدام قاعدة البيانات المتجهات لتخزين هذه العلاقات وبحثها بسهولة.\n\nبشكل عام، القاعدة البيانات المتجهة تستخدم في العديد من التطبيقات مثل: \n\n1. التعامل مع البيانات الاجتماعية (مثل معلومات التواصل الاجتماعي)\n2. التحليل البيئي (الذي يتعامل مع البيانات المتعلقة بالمناخ والبيئة)\n3. البحث العلمي (الذي يتعامل مع البيانات التي تتضمن العلاقات بين الأشخاص أو الأشياء)\n4. تطوير الاتجاهات في الأعمال التجارية (مثل تحديد العلامات التجارية وتحليل التغيرات في السوق)\n\nبشكل عام، القاعدة البيانات المتجهة هي مفهوم مهم في مجال البيانات الكبيرة والذكاء الصناعي حيث تستخدم لمعالجة البيانات التي تتكون من العلاقات والتفاعلات بين الأشياء.,981.25,Retrieval \nAugmented \nGeneration \n(RAG)\nDr. Tamer Arafa\n\nhelp you respond. <retrieved articles>”\nRetriever\nKnowledge \nBase\n14\n\nSearch Techniques\n1. Document A\n2. Document B\n3. Document C\n4. Document D\n…\n1. Document C\n2. Document B\n3. Document X\n4. Document Y\n…\n1. Document A\n2. Document B\n3. Document C\n4. Document D\n…\n1. Document C\n2. Document B\n3. Document X\n4. Document Y\n…\nKeyword \nSearch\nSemantic \nSearch\n\nRespond based on \nyour knowledge\nSynthesize \nresearch\n2,12

In [139]:
evaluater_A = pd.merge(evaluater_A, chat_df1, on='query_number', how='inner')

In [140]:
evaluater_A.head(1)

,Relevance,Faithfulness,Latency,Readability,Preplexity,date,query_number,question,answer,execution_time_seconds,retrieved_context
0,0,0,0,3,2,2026/06/08,0,"اشرح retriever, بالأمثلة",أنا أعتذر، ولكن في هذه الحالة لا يمكنني مساعدتك. المعلومات التي تحتاجها لا تظهر في المحتوى الذي تم تحميل.,197.31,Retrieval \nAugmented \nGeneration \n(RAG)\nDr. Tamer Arafa\n\nhelp you respond. <retrieved articles>”\nRetriever\nKnowledge \nBase\n14\n\nMiss valuable information\n●\nNo perfect solution\nRetriever usually doesn’t perfectly rank documents\n●\nMonitor and experiment\nChange settings to find what works\n19\n\nRetrieval Augmented Generation\n9

In [141]:
evaluater_B = pd.merge(evaluater_B, chat_df1, on='query_number', how='inner')

In [142]:
evaluater_B.head(1)

,Relevance,Faithfulness,Latency,Readability,Preplexity,date,query_number,question,answer,execution_time_seconds,retrieved_context
0,0,3,3,3,3,2026/06/08,0,"اشرح retriever, بالأمثلة",أنا أعتذر، ولكن في هذه الحالة لا يمكنني مساعدتك. المعلومات التي تحتاجها لا تظهر في المحتوى الذي تم تحميل.,197.31,Retrieval \nAugmented \nGeneration \n(RAG)\nDr. Tamer Arafa\n\nhelp you respond. <retrieved articles>”\nRetriever\nKnowledge \nBase\n14\n\nMiss valuable information\n●\nNo perfect solution\nRetriever usually doesn’t perfectly rank documents\n●\nMonitor and experiment\nChange settings to find what works\n19\n\nRetrieval Augmented Generation\n9

In [143]:
evaluater_A.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0    Relevance              13 non-null     int64
 1   Faithfulness            13 non-null     int64
 2    Latency                13 non-null     int64
 3   Readability             13 non-null     int64
 4   Preplexity              13 non-null     int64
 5   date                    13 non-null     object
 6   query_number            13 non-null     int64
 7   question                13 non-null     object
 8   answer                  13 non-null     object
 9   execution_time_seconds  13 non-null     float64
 10  retrieved_context       13 non-null     object
dtypes: float64(1), int64(6), object(4)
memory usage: 1.2+ KB

In [144]:
evaluation_data1=pd.concat([evaluater_A,evaluater_B])

In [145]:
evaluation_data1.head(1)

,Relevance,Faithfulness,Latency,Readability,Preplexity,date,query_number,question,answer,execution_time_seconds,retrieved_context
0,0,0,0,3,2,2026/06/08,0,"اشرح retriever, بالأمثلة",أنا أعتذر، ولكن في هذه الحالة لا يمكنني مساعدتك. المعلومات التي تحتاجها لا تظهر في المحتوى الذي تم تحميل.,197.31,Retrieval \nAugmented \nGeneration \n(RAG)\nDr. Tamer Arafa\n\nhelp you respond. <retrieved articles>”\nRetriever\nKnowledge \nBase\n14\n\nMiss valuable information\n●\nNo perfect solution\nRetriever usually doesn’t perfectly rank documents\n●\nMonitor and experiment\nChange settings to find what works\n19\n\nRetrieval Augmented Generation\n9

In [162]:
evaluation_data1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26 entries, 0 to 12
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0    Relevance              26 non-null     int64
 1   Faithfulness            26 non-null     int64
 2    Latency                26 non-null     int64
 3   Readability             26 non-null     int64
 4   Preplexity              26 non-null     int64
 5   date                    26 non-null     object
 6   query_number            26 non-null     int64
 7   question                26 non-null     object
 8   answer                  26 non-null     object
 9   execution_time_seconds  26 non-null     float64
 10  retrieved_context       26 non-null     object
dtypes: float64(1), int64(6), object(4)
memory usage: 2.4+ KB

In [147]:
#rename to handle space in columns names

In [148]:
evaluation_data1.to_csv('evaluation_data1.csv',index=False)

# Evaluated Chat2

In [149]:
evaluater_A2= pd.read_csv('Evaluation2_mervat.csv')
evaluater_B2= pd.read_csv('Evaluation2_nesreen.csv')
chat_df2= pd.read_csv('chat_df2.csv')

In [150]:
dfs_names=['evaluater_A2','evaluater_B2','chat_df2']
chat2_dfs=[evaluater_A2,evaluater_B2,chat_df2]
for name,df  in zip(dfs_names,chat2_dfs):
    print(f"Dataframe Name: {name}")
    print("-" * 50)
    display(df.info(),df.head(1),df.tail(1))

Dataframe Name: evaluater_A2
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    query_number  14 non-null     int64
 1    Relevance     14 non-null     int64
 2   Faithfulness   14 non-null     int64
 3    Latency       14 non-null     int64
 4   Readability    14 non-null     int64
 5   Preplexity     14 non-null     int64
 6   date           14 non-null     object
dtypes: int64(6), object(1)
memory usage: 916.0+ bytes

None

,query_number,Relevance,Faithfulness,Latency,Readability,Preplexity,date
0,1,2,2,1,2,2,2026/06/09

,query_number,Relevance,Faithfulness,Latency,Readability,Preplexity,date
13,14,0,0,0,0,0,2026/06/09

Dataframe Name: evaluater_B2
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    query_number  14 non-null     int64
 1    Relevance     14 non-null     int64
 2   Faithfulness   14 non-null     int64
 3    Latency       14 non-null     int64
 4   Readability    14 non-null     int64
 5   Preplexity     14 non-null     int64
 6   date           14 non-null     object
dtypes: int64(6), object(1)
memory usage: 916.0+ bytes

None

,query_number,Relevance,Faithfulness,Latency,Readability,Preplexity,date
0,1,3,2,2,2,1,2026/06/08

,query_number,Relevance,Faithfulness,Latency,Readability,Preplexity,date
13,14,0,0,0,0,0,2026/06/08

Dataframe Name: chat_df2
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   question                13 non-null     object
 1   answer                  13 non-null     object
 2   execution_time_seconds  13 non-null     float64
 3   retrieved_context       13 non-null     object
dtypes: float64(1), object(3)
memory usage: 548.0+ bytes

None

,question,answer,execution_time_seconds,retrieved_context
0,"اشرح ما هو الفرق بين dense vector , sparse vector","في البحث عن الكلمات، يتم استخدام مصطلح ""الvector"" أو ""المصفوفة"". في هذا السياق، يُستخدم المصطلح بطرق مختلفة. \n\n- **Sparse Vector**: يشير إلى أن معظم الكلمات لا تظهر بشكل كبير في النص (أي أنها غير مرتبطة بالكلمات الرئيسية). في حالة ""البندز"" أو ""البند""، فإن هذه الكلمات تكون محدودة وليست عادةً مرتبطة ببعضها البعض. \n\n- **Dense Vector**: يشير إلى أن معظم الكلمات تظهر بشكل كبير في النص (أي أنها مرتبطة بالكلمات الرئيسية). في حالة ""البندز"" أو ""البند""، فإن هذه الكلمات تكون مرتبطة بكثير من الكلمات الرئيسية.\n\nفي الواقع، لا يوجد فرق كبير بينهما في عملية البحث عن الكلمات. الفرق يعتمد على كيفية استخدام البيانات وطبيعة النص الذي يتم البحث عنه.",336.29,"[Slide 31]\nSparse Vectors\nMost words aren’t used. The bag of words is sparse, with few non-zero entries.\n“Making pizza without a pizza oven”\nmaking \n1\npizza \n1\nwithout \n1\na \n1\ncake \n0\ndrink \n0\npan \n0\npasta \n0\noven \n1\npan \n0\npasta \n0\nwith \n0\ntea \n0\nburger \n0\nsalad \n0\ntaco \n0\nblend \n0\nthe \n0\n31\n\n[Slide 77]\nTypical Vector Database Operations\n●\nDatabase setup\n●\nLoad documents\n●\nCreate sparse vectors for keyword search\n●\nCreate dense vectors for semantic search\n●\nCreate HNSW index to power ANN algorithm\n●\nRun searches!\n77\n\n[Slide 71]\nSearch Algorithm\nNo closer \nneighbors\nQuery \nVector\n71\n\n[Slide 66]\nSearch Algorithm\nQuery \nVector\n66"

,question,answer,execution_time_seconds,retrieved_context
12,thank you,"You're welcome! If you have any more questions or need further clarification, feel free to ask.",435.29,"[Slide 35]\nHaving an LLM initiate a clothing return\nShopBot\nSure, its tim.b@email.net\nThank you! I’ve just sent \nthe shipping label to your \nemail address. Please \nreturn your jeans within \nthe next 5 days.\nT\nGreat, thank you!\nT\nYou’re welcome!\nAPI call to the\nshipper\n35\n\n[Slide 33]\nHaving an LLM initiate a clothing return\nShopBot\nOf course, I’d be happy \nto help you. Can you tell \nme your order number?\nHi there! How can I help \nyou today?\nI need to return a pair of \njeans that I purchased\nT\nSure, it’s 21104.\nT\n33\n\n[Slide 63]\nBuilding up the ReAct prompt\nQuestion\nThought\nAction\nObservation\nQuestion \nThought\nAction \nObservation\nReAct example\nInstructions\nQuestion to be \nanswered\nLLM\n(could be more \nthan one \nexample)\n63\n\n[Slide 19]\nLLM-powered applications\nLLM\nUser Prompt\nCompletion\n19"

In [151]:
# delete extra/null rows
evaluater_A2 = evaluater_A2.iloc[:-1]
evaluater_B2 = evaluater_B2.iloc[:-1]

In [152]:
eval_dfs=[evaluater_A2,evaluater_B2]
eval_dfs_names=['evaluater_A2','evaluater_B2']
for df,name  in zip(eval_dfs,eval_dfs_names):
    print(f"Dataframe Name: {name}")
    print("-" * 50)
    display(df.info(),df.tail(1))

Dataframe Name: evaluater_A2
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    query_number  13 non-null     int64
 1    Relevance     13 non-null     int64
 2   Faithfulness   13 non-null     int64
 3    Latency       13 non-null     int64
 4   Readability    13 non-null     int64
 5   Preplexity     13 non-null     int64
 6   date           13 non-null     object
dtypes: int64(6), object(1)
memory usage: 860.0+ bytes

None

,query_number,Relevance,Faithfulness,Latency,Readability,Preplexity,date
12,13,3,3,1,3,3,2026/06/09

Dataframe Name: evaluater_B2
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    query_number  13 non-null     int64
 1    Relevance     13 non-null     int64
 2   Faithfulness   13 non-null     int64
 3    Latency       13 non-null     int64
 4   Readability    13 non-null     int64
 5   Preplexity     13 non-null     int64
 6   date           13 non-null     object
dtypes: int64(6), object(1)
memory usage: 860.0+ bytes

None

,query_number,Relevance,Faithfulness,Latency,Readability,Preplexity,date
12,13,3,3,1,3,3,2026/06/08

In [153]:
evaluater_A2.columns

Index([' query_number', ' Relevance', 'Faithfulness', ' Latency',
       'Readability', 'Preplexity', 'date '],
      dtype='object')

In [154]:
evaluater_A2=evaluater_A2.drop(columns=[' query_number'],axis=1)
evaluater_B2=evaluater_B2.drop(columns=[' query_number'],axis=1)

In [155]:
evaluater_A2['query_number'] = evaluater_A2.index
evaluater_B2['query_number'] = evaluater_B2.index

In [159]:
eval_dfs=[evaluater_A2,evaluater_B2]
eval_dfs_names=['evaluater_A2','evaluater_B2']
for df,name  in zip(eval_dfs,eval_dfs_names):
    print(f"Dataframe Name: {name}")
    print("-" * 50)
    display(df.info(),df.head(1),df.tail(1))

Dataframe Name: evaluater_A2
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    Relevance    13 non-null     int64
 1   Faithfulness  13 non-null     int64
 2    Latency      13 non-null     int64
 3   Readability   13 non-null     int64
 4   Preplexity    13 non-null     int64
 5   date          13 non-null     object
 6   query_number  13 non-null     int64
dtypes: int64(6), object(1)
memory usage: 860.0+ bytes

None

,Relevance,Faithfulness,Latency,Readability,Preplexity,date,query_number
0,2,2,1,2,2,2026/06/09,0

,Relevance,Faithfulness,Latency,Readability,Preplexity,date,query_number
12,3,3,1,3,3,2026/06/09,12

Dataframe Name: evaluater_B2
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    Relevance    13 non-null     int64
 1   Faithfulness  13 non-null     int64
 2    Latency      13 non-null     int64
 3   Readability   13 non-null     int64
 4   Preplexity    13 non-null     int64
 5   date          13 non-null     object
 6   query_number  13 non-null     int64
dtypes: int64(6), object(1)
memory usage: 860.0+ bytes

None

,Relevance,Faithfulness,Latency,Readability,Preplexity,date,query_number
0,3,2,2,2,1,2026/06/08,0

,Relevance,Faithfulness,Latency,Readability,Preplexity,date,query_number
12,3,3,1,3,3,2026/06/08,12

In [164]:
chat_df2.columns

Index(['question', 'answer', 'execution_time_seconds', 'retrieved_context'], dtype='object')

In [165]:
chat_df2['query_number'] = chat_df2.index

In [166]:
evaluater_A2 = pd.merge(evaluater_A2, chat_df2, on='query_number', how='inner')
evaluater_B2 = pd.merge(evaluater_B2, chat_df2, on='query_number', how='inner')

In [167]:
evaluation_data2=pd.concat([evaluater_A2,evaluater_B2])

In [168]:
evaluation_data2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26 entries, 0 to 12
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0    Relevance              26 non-null     int64
 1   Faithfulness            26 non-null     int64
 2    Latency                26 non-null     int64
 3   Readability             26 non-null     int64
 4   Preplexity              26 non-null     int64
 5   date                    26 non-null     object
 6   query_number            26 non-null     int64
 7   question                26 non-null     object
 8   answer                  26 non-null     object
 9   execution_time_seconds  26 non-null     float64
 10  retrieved_context       26 non-null     object
dtypes: float64(1), int64(6), object(4)
memory usage: 2.4+ KB

In [169]:
evaluation_data2.to_csv('evaluation_data2.csv',index=False)

In [170]:
all_evaluationData=pd.concat([evaluation_data1,evaluation_data2])

In [171]:
all_evaluationData.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52 entries, 0 to 12
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0    Relevance              52 non-null     int64
 1   Faithfulness            52 non-null     int64
 2    Latency                52 non-null     int64
 3   Readability             52 non-null     int64
 4   Preplexity              52 non-null     int64
 5   date                    52 non-null     object
 6   query_number            52 non-null     int64
 7   question                52 non-null     object
 8   answer                  52 non-null     object
 9   execution_time_seconds  52 non-null     float64
 10  retrieved_context       52 non-null     object
dtypes: float64(1), int64(6), object(4)
memory usage: 4.9+ KB

In [172]:
all_evaluationData = all_evaluationData.reset_index(drop=True)

In [174]:
all_evaluationData.sample(1)

,Relevance,Faithfulness,Latency,Readability,Preplexity,date,query_number,question,answer,execution_time_seconds,retrieved_context
46,3,0,2,3,3,2026/06/08,7,ازاي استخدم LLMs فى تطبيقات عَملية,استخدام LLMs في التطبيقات يعني استخدام هذه الأنظمة الحيوية للتعلم الآلي لتقديم خدمات وتطبيقات متنوعة. لذا، يمكننا استخدامها في العديد من المجالات مثل:\n\n1. التصنيف: لتحليل البيانات وتقديم تصنيفات دقيقة.\n2. البحث والتنقل: لمساعدة المستخدمين في العثور على المعلومات أو الأشياء التي يبحثون عنها.\n3. التحليل السمعي: لتحسين تجربة الاستماع للأشخاص الذين يستخدمون الأجهزة اللوحية.\n4. التعلم الآلي: لتقديم خدمات التعلم والتعليم عبر الإنترنت.\n\nLLMs يمكن أن تكون مفيدة في العديد من التطبيقات، حيث تساعد في تقديم نتائج دقيقة وفعالة، مما يحسن تجربة المستخدم ويقلل من الحاجة إلى العمليات البشرية.,518.59,[Slide 1]\nOptimize LLMs \nand build \ngenerative AI \napplications\nDr. Tamer Arafa\n\n[Slide 44]\nLLMs can struggle with mathematics\nWhat is 40366 / 439?\nLLM\nPrompt\nModel\nCompletion\nWhat is 40366 / 439?\n92.549\n44\n\n[Slide 7]\nLLM optimization techniques\nQuantization\nPruning\nDistillation\nLLM\nTeacher\nLLM\nStudent\nLLM\n16-bit \nquantized \nLLM\nLLM\nPruned \nLLM\n7\n\n[Slide 6]\nLLM optimization techniques\nQuantization\nPruning\nDistillation\nLLM\nTeacher\nLLM\nStudent\nLLM\n16-bit \nquantized \nLLM\nLLM\nPruned \nLLM\n6

In [176]:
all_evaluationData.columns

Index([' Relevance', 'Faithfulness', ' Latency', 'Readability', 'Preplexity',
       'date ', 'query_number', 'question', 'answer', 'execution_time_seconds',
       'retrieved_context'],
      dtype='object')

In [177]:
#handel space in cols names
all_evaluationData=all_evaluationData.rename(
columns={ ' Relevance':'Relevance',
         ' Latency':'Latency'
    
}
)

In [178]:
all_evaluationData.to_csv('all_evaluationData.csv',index=False)

In [181]:
all_evaluationData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Relevance               52 non-null     int64
 1   Faithfulness            52 non-null     int64
 2   Latency                 52 non-null     int64
 3   Readability             52 non-null     int64
 4   Preplexity              52 non-null     int64
 5   date                    52 non-null     object
 6   query_number            52 non-null     int64
 7   question                52 non-null     object
 8   answer                  52 non-null     object
 9   execution_time_seconds  52 non-null     float64
 10  retrieved_context       52 non-null     object
dtypes: float64(1), int64(6), object(4)
memory usage: 4.6+ KB

## Calculate Inter-Annotator Agreement

In [179]:
evaluater_A.columns

Index([' Relevance', 'Faithfulness', ' Latency', 'Readability', 'Preplexity',
       'date ', 'query_number', 'question', 'answer', 'execution_time_seconds',
       'retrieved_context'],
      dtype='object')

In [182]:
evaluater_B.columns

Index([' Relevance', 'Faithfulness', ' Latency', 'Readability', 'Preplexity',
       'date ', 'query_number', 'question', 'answer', 'execution_time_seconds',
       'retrieved_context'],
      dtype='object')

In [183]:
evaluater_A2.columns

Index([' Relevance', 'Faithfulness', ' Latency', 'Readability', 'Preplexity',
       'date ', 'query_number', 'question', 'answer', 'execution_time_seconds',
       'retrieved_context'],
      dtype='object')

In [184]:
evaluater_A2.columns

Index([' Relevance', 'Faithfulness', ' Latency', 'Readability', 'Preplexity',
       'date ', 'query_number', 'question', 'answer', 'execution_time_seconds',
       'retrieved_context'],
      dtype='object')

In [185]:
evaluater_A2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0    Relevance              13 non-null     int64
 1   Faithfulness            13 non-null     int64
 2    Latency                13 non-null     int64
 3   Readability             13 non-null     int64
 4   Preplexity              13 non-null     int64
 5   date                    13 non-null     object
 6   query_number            13 non-null     int64
 7   question                13 non-null     object
 8   answer                  13 non-null     object
 9   execution_time_seconds  13 non-null     float64
 10  retrieved_context       13 non-null     object
dtypes: float64(1), int64(6), object(4)
memory usage: 1.2+ KB

In [187]:
evaluater_B2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0    Relevance              13 non-null     int64
 1   Faithfulness            13 non-null     int64
 2    Latency                13 non-null     int64
 3   Readability             13 non-null     int64
 4   Preplexity              13 non-null     int64
 5   date                    13 non-null     object
 6   query_number            13 non-null     int64
 7   question                13 non-null     object
 8   answer                  13 non-null     object
 9   execution_time_seconds  13 non-null     float64
 10  retrieved_context       13 non-null     object
dtypes: float64(1), int64(6), object(4)
memory usage: 1.2+ KB

In [193]:
all_evaluaterA=pd.concat([evaluater_A,evaluater_A2])
all_evaluaterB=pd.concat([evaluater_B,evaluater_B2])

In [196]:
all_evaluaterA.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26 entries, 0 to 12
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0    Relevance              26 non-null     int64
 1   Faithfulness            26 non-null     int64
 2    Latency                26 non-null     int64
 3   Readability             26 non-null     int64
 4   Preplexity              26 non-null     int64
 5   date                    26 non-null     object
 6   query_number            26 non-null     int64
 7   question                26 non-null     object
 8   answer                  26 non-null     object
 9   execution_time_seconds  26 non-null     float64
 10  retrieved_context       26 non-null     object
dtypes: float64(1), int64(6), object(4)
memory usage: 2.4+ KB

In [194]:
columns_to_evaluate = [' Relevance', 'Faithfulness', ' Latency', 'Readability', 'Preplexity']

In [198]:
all_evaluater_a_labels = np.concatenate([all_evaluaterA[col].values for col in columns_to_evaluate])
all_evaluater_b_labels = np.concatenate([all_evaluaterB[col].values for col in columns_to_evaluate])

overall_kappa = cohen_kappa_score(all_evaluater_a_labels, all_evaluater_b_labels,weights='linear')

print(f"Overall Cohen's Kappa Score: {overall_kappa:.4f}")
if overall_kappa > 0.80:
    print("Interpretation: Almost Perfect Agreement! Your guidelines are rock solid.")
elif overall_kappa > 0.60:
    print("Interpretation: Substantial Agreement. Highly reliable evaluation data.")
elif overall_kappa > 0.40:
    print("Interpretation: Moderate Agreement. Consider clarifying borderline rubric rules.")
else:
    print("Interpretation: Poor Agreement. Raters are misaligned. Stop and retrain them.")

Overall Cohen's Kappa Score: 0.4752
Interpretation: Moderate Agreement. Consider clarifying borderline rubric rules.

In [200]:
import numpy as np
import pandas as pd
from sklearn.metrics import cohen_kappa_score

# قائمة الأعمدة بدقة
columns_to_evaluate = [' Relevance', 'Faithfulness', ' Latency', 'Readability', 'Preplexity']

print(f"{'Criterion':<15} | {'Weighted Kappa (Linear)':<23}")
print("-" * 62)

for col in columns_to_evaluate:
    evaluaterA = all_evaluaterA[col].values
    evaluaterB = all_evaluaterB[col].values
    
    kappa_linear = cohen_kappa_score(evaluaterA, evaluaterB, weights='linear')
    
    print(f"{col.strip():<15}  | {kappa_linear:>22.4f}")

Criterion       | Weighted Kappa (Linear)
--------------------------------------------------------------
Relevance        |                 0.3232
Faithfulness     |                 0.4104
Latency          |                 0.1492
Readability      |                 0.6803
Preplexity       |                 0.4476